// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import broker "github.com/rafalmnich/broker"
import mock "github.com/stretchr/testify/mock"

// Performer is an autogenerated mock type for the Performer type
type Performer struct {
	mock.Mock
}

// MakeActions provides a mock function with given fields: actions
func (_m *Performer) MakeActions(actions broker.Actions) error {
	ret := _m.Called(actions)

	var r0 error
	if rf, ok := ret.Get(0).(func(broker.Actions) error); ok {
		r0 = rf(actions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
