// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import broker "github.com/rafalmnich/broker"
import mock "github.com/stretchr/testify/mock"

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: actions
func (_m *Publisher) Publish(actions broker.Actions) error {
	ret := _m.Called(actions)

	var r0 error
	r0 = ret.Error(0)

	return r0
}
